config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    # public/homes
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    # public/items
    resources :items, only: [:index, :show]

    # public/customers
    get 'customers/my_page' => 'customers#show', as: "show"
    get 'customers/information/edit' => 'customers#edit', as: "edit"
    patch 'customers/information' => 'customers#update', as: "update"
    get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"

    # public/cart_items
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # public/orders
    post 'orders/confirm' => "orders#confirm", as: "confirm"
    get 'orders/complete' => "orders#complete", as: "complete"
    resources :orders, only: [:new, :index, :show, :create]

    # public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    # admin/homes
    get '/' => "homes#top", as: "top"

    # admin/items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # admin/genres
    resources :genres, only: [:index, :create, :edit, :update]

    # admin/customers
    resources :customers, only: [:index, :show, :edit, :update]

    # admin/orders
    resources :orders, only: [:show, :update]

    # admin/order_details
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # devise_for :admin, controllers: {
  # sessions: "admin/sessions"
  # }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # customer（1）はaddress（N）を複数持っている
  has_many :addresses
  # customer（1）はcart_item（N）を複数持っている
  has_many :cart_items
  # customer（1）はorder（N）を複数持っている
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # 会員フルネーム（漢字）用のメソッド
  def full_name
   self.last_name + " " + self.first_name
  end

  # 会員フルネーム（カナ）用のメソッド
  def full_name_kana
   self.last_name_kana + " " + self.first_name_kana
  end

  enum is_deleted: { no_active: true, active: false}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

  def index
   # customersテーブルに保存されている全てのデータを取得する
   @customers = Customer.page(params[:page])
  end

  def show
   # レコードを1件だけ取得
   @customer = Customer.find(params[:id])
  end

  def edit
   # レコードを1件だけ取得
   @customer = Customer.find(params[:id])
  end

  def update
   # レコードを1件だけ取得
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
   # 会員詳細画面にリダイレクト
   redirect_to admin_customer_path(@customer.id)
  end

  private
  # 顧客データのストロングパラメータ
  def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row">
  <style>
   label {
    width: 140px;
    margin: 0 40px 20px 20px;
   }

   .style {
    margin-right: 5%;
   }

   .address {
    width: 60%;
   }

   text {
    padding-right: 15px;
   }

   /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
   @media screen and (max-width:768px) {
    h3 {
     font-size: 20px;
    }

    label {
     width: 100px;
     margin: 0 2% 20px 20px;
    }

    .field, .btn-success {
     font-size: 13px;
    }

    .text_field, .style {
      width: 100px;
    }

   }

  </style>

  <div class="col-lg-10 col-md-12 mx-auto">
   <h3 style="padding: 10px 0 4%">
    <span style="background-color: #e6dcdf;">
     <%= @customer.full_name %>さんの会員情報編集
    </span>
   </h3>

   <!-- 画面遷移先は会員詳細画面（show）のため、URLはadmin_customer_pathとなる -->
   <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <div class="field">
     <%= f.label :id, "会員ID" %>
     <%= @customer.id %>
    </div>

    <div class="field">
     <%= f.label :full_name, "氏名" %>
     <%= f.text_field :last_name, class: "style" %>
     <%= f.text_field :first_name, class: "text_field" %>
    </div>

    <div class="field">
     <%= f.label :full_name_kana, "フリガナ" %>
     <%= f.text_field :last_name_kana, class: "style" %>
     <%= f.text_field :first_name_kana, class: "text_field" %>
    </div>

    <div class="field">
     <%= f.label :postal_code, "郵便番号" %>
     <%= f.text_field :postal_code, class: "text_field" %>
    </div>

    <div class="field">
     <%= f.label :address, "住所" %>
     <%= f.text_field :address, class: "address" %>
    </div>

    <div class="field">
     <%= f.label :telephone_number, "電話番号" %>
     <%= f.text_field :telephone_number, class: "text_field" %>
    </div>

    <div class="field">
     <%= f.label :email, "メールアドレス" %>
     <%= f.text_field :email, class: "text_field" %>
    </div>

    <div class="field">
     <%= f.label :is_deleted, "会員ステータス" %>
     <%= f.radio_button :is_deleted, "active" %> <text>有効</text>
     <%= f.radio_button :is_deleted, "no_active" %> <text>退会</text>
    </div>

    <div class="field">
      <label></label>
     <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>

   <% end %>

 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <style>
   thead {
    color: rgba(0, 0, 0, 0.6);
    background-color: #e6dcdf;
   }

   .active, .no_active {
    font-weight: bold;
   }

   .pagination {
    justify-content: center;
   }

   span {
    margin-right: 10px;
   }

   /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
   @media screen and (max-width: 768px) {
    h3 {
     font-size: 20px;
    }

    .table-inverse {
     font-size: 13px;
    }
   }
  </style>

  <div class="col-12 mx-auto">
   <h3 style="padding: 10px 0 3% 5%;">
    <span style="background-color: #e6dcdf;">会員一覧</span>
   </h3>
  </div>

  <div class="col-lg-10 col-md-10 mx-auto">
   <table class="table table-inverse">
    <thead>
     <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr>
    </thead>

    <tbody style="color: rgba(0, 0, 0, 0.6);">
     <% @customers.each do |customer| %>
      <tr>
       <td>
        <%= customer.id %>
       </td>
       <td>
        <%= link_to customer.full_name, admin_customer_path(customer.id) %>
       </td>
       <td>
        <%= customer.email %>
       </td>

       <% if customer.is_deleted == "active" %>
        <td class="active", style="color: #28a745;">
         <%= customer.is_deleted_i18n %>
        </td>
       <% else %>
        <td class="no_active">
         <%= customer.is_deleted_i18n %>
        </td>
       <% end %>

      </tr>
     <% end %>
    </tbody>

   </table>

   <%= paginate @customers %>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row">
  <style>
   label {
    width: 140px;
    margin: 0 40px 20px 20px;
   }

   .btn-success {
    margin-right: 60px;
   }

   /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
   @media screen and (max-width:768px) {
    h3 {
     font-size: 20px;
    }

    label {
     width: 95px;
    }

    .field, .btn-success, .btn-primary {
     font-size: 13px;
    }

    .btn-success {
     margin-right: 2%;
    }
   }

  </style>

  <div class="col-lg-10 col-md-10 mx-auto">
   <h3 style="padding: 10px 0 4%">
    <span style="background-color: #e6dcdf;">
     <%= @customer.full_name %>さんの会員詳細
    </span>
   </h3>

   <div class="field">
    <label for="admin_customer_id">会員ID</label>
    <%= @customer.id %>
   </div>

   <div class="field">
    <label for="admin_customer_name">氏名</label>
     <%= @customer.full_name %>
   </div>

   <div class="field">
    <label for="admin_customer_name_kana">フリガナ</label>
    <%= @customer.full_name_kana %>
   </div>

   <div class="field">
    <label for="admin_postal_code">郵便番号</label>
    <%= @customer.postal_code %>
   </div>

   <div class="field">
    <label for="admin_address">住所</label>
    <%= @customer.address %>
   </div>

   <div class="field">
    <label for="admin_telephone_number">電話番号</label>
    <%= @customer.telephone_number %>
   </div>

   <div class="field">
    <label for="admin_email">メールアドレス</label>
    <%= @customer.email %>
   </div>

   <div class="field">
    <label for="admin_is_deleted">会員ステータス</label>
    <%= @customer.is_deleted_i18n %>
   </div>

   <div class="actions">
    <label></label>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
    <%= link_to "注文履歴一覧を見る", admin_top_path, class: "btn btn-primary" %>
   </div>

  </div>
 </div>
</div>