config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    # public/homes
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    # public/items
    resources :items, only: [:index, :show]

    # public/customers
    get 'customers/my_page' => 'customers#show', as: "show"
    get 'customers/information/edit' => 'customers#edit', as: "edit"
    patch 'customers/information' => 'customers#update', as: "update"
    get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"

    # public/cart_items
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # public/orders
    post 'orders/confirm' => "orders#confirm", as: "confirm"
    get 'orders/complete' => "orders#complete", as: "complete"
    resources :orders, only: [:new, :index, :show, :create]

    # public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    # admin/homes
    get '/' => "homes#top", as: "top"

    # admin/items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # admin/genres
    resources :genres, only: [:index, :create, :edit, :update]

    # admin/customers
    resources :customers, only: [:index, :show, :edit, :update]

    # admin/orders
    resources :orders, only: [:show, :update]

    # admin/order_details
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # devise_for :admin, controllers: {
  # sessions: "admin/sessions"
  # }

end

app/models/order.rb
class Order < ApplicationRecord
 # order（N）はcustomer（1）に属する
 belongs_to :customer
 # order（1）はorder_detail（N）を複数持っている
 has_many :order_details

 # 小計を求めるメソッド
 def subtotal
  item.with_tax_price * amount
 end

 enum order_status: { wait: 0, deposited: 1, make: 2, preparation: 3, sent: 4 }
 enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!

  def show
   # レコードを1件だけ取得
   @order = Order.find(params[:id])
   # 配送料は800円
   @shipping_fee = 800

   @total = 0
   # order.idに紐づく全ての注文詳細を出す
   @order.order_details.each do |order_detail|
    # order_detail.purchase_amountに購入時価格（カートに入れていた商品の小計）が入っている
    @total += order_detail.purchase_amount
   end
  end

  def update
   # レコードを1件だけ取得
   @order = Order.find(params[:id])
   # 更新する
   @order.update(order_params)

   # 注文ステータスが「入金確認（deposited）」の場合
   if @order.order_status == "deposited"
    # 全ての製作ステータスを「製作待ち（wait）」に更新する
    @order.order_details.update_all(crafting_status: "wait")
   end
   # 注文履歴詳細にリダイレクト
   redirect_to admin_order_path(@order.id)
  end

  # 消費税を求めるメソッド
  def with_tax_price
   (price * 1.1).floor
  end

  private
  # 注文データのストロングパラメータ
  def order_params
   params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row">
  <style>
   label {
    font-weight: bold;
    width: 150px;
    margin: 8px 0;
   }

   .customer, .price {
    font-size: 18px;
   }

   .btn-success {
    margin-right: 40px;
   }

   thead {
    color: rgba(0, 0, 0, 0.6);
    background-color: #e6dcdf;
   }

   select {
    width: 120px;
    height: 35px;
    margin-right: 20px;
   }

   .price {
    margin-left: 60px;
   }

   .item {
    width: 250px;
   }

   .item_price {
    width: 140px;
   }

   .quantity, .purchase_amount {
    width: 70px;
   }

   .crafting_status {
    width: 300px;
   }

   /* タブレット横置きサイズ（1024px）以下の際に適用される設定 */
   @media screen and (max-width:1024px) {
    .price {
     margin: 20px 0 0;
    }

    .customer, .price, table {
     font-size: 15px;
    }

    select {
     width: 100px;
    }
   }

   /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
   @media screen and (max-width:768px) {
    h3 {
     font-size: 20px;
    }

    .customer, .price, table {
     font-size: 13px;
    }

    label {
     font-weight: bold;
     width: 120px;
     margin: 8px 0;
    }

    select {
     width: 75px;
     margin-bottom: 10px;
    }

   .item {
    width: 310px;
   }

   .item_price {
    width: 140px;
   }

   .quantity, .purchase_amount {
    width: 70px;
   }

   .crafting_status {
    width: 130px;
   }
   }

  </style>

  <div class="col-12 mx-auto">
   <h3 style="padding: 10px 0 2% 10%">
    <span style="background-color: #e6dcdf;">
     注文履歴詳細
    </span>
   </h3>

   <div class="customer">
    <div class="field">
     <label for="customer_full_name">購入者</label>
     <%= link_to @order.customer.full_name, admin_customer_path(@order.customer_id) %>
    </div>

    <div class="field">
     <label for="order_datetime">注文日</label>
     <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>

    <div class="field">
     <label for="order_address_name">配送先</label>
     〒<%= @order.postal_code %>
     <%= @order.address %></br>
     <label></label> <%= @order.name %>
    </div>

    <div class="field" style="margin-top: 10px;">
     <label for="order_payment_method">支払方法</label>
     <%= @order.payment_method_i18n %>
    </div>

    <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
     <div class="field">
      <%= f.label :order_status, "注文ステータス" %>
      <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
      <%= f.submit "更新", class: "btn btn-success" %>
     </div>
    <% end %>
   </div>
  </div>

  <div class="col-lg-8 col-md-12" style="margin-top: 40px;">
   <table class="table table-inverse">

    <thead>
     <tr>
      <th class="item">商品名</th>
      <th class="item_price">単価（税込）</th>
      <th class="quantity">数量</th>
      <th class="purchase_amount">小計</th>
      <th class="crafting_status">製作ステータス</th>
     </tr>
    </thead>

    <tbody style="color: rgba(0, 0, 0, 0.6);">
     <% @order.order_details.each do |order_detail| %>
      <tr>
       <!-- 商品名 -->
       <td style="padding-top: 20px;">
        <%= order_detail.item.name %>
       </td>

       <!-- 単価（税込）-->
       <td style="padding: 20px;">
        <%= order_detail.item.with_tax_price.to_s(:delimited) %>
       </td>

       <!-- 数量 -->
       <td style="padding: 20px;">
        <%= order_detail.quantity %>
       </td>

       <!-- 小計 -->
       <td style="padding-top: 20px;">
        <%= order_detail.purchase_amount.to_s(:delimited) %>
       </td>

       <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
        <td style="padding-top: 20px;">
         <!-- 製作ステータス -->
         <%= f.select :crafting_status, OrderDetail.crafting_statuses.keys.map {|k| [I18n.t("enums.order_details.crafting_status.#{k}"), k]} %>
         <!-- 更新ボタン -->
         <%= f.submit "更新", class: "btn btn-success" %>
        </td>
       <% end %>

      </tr>
     <% end %>
    </tbody>
   </table>
  </div>

  <div class="col-lg-4 col-md-12" style="display: flex; justify-content:flex-end; flex-flow: column; bottom: 20px;">
   <div class="price">
    <div class="field">
     <label for="total">商品合計</label>
     <%= @total.to_s(:delimited) %>円
    </div>

    <div class="field">
     <label for="shipping_fee">送料</label>
     <%= @shipping_fee %>円
    </div>

    <div class="field">
     <label for="bill">請求金額合計</label>
     <%= @order.bill.to_s(:delimited) %>円
    </div>
   </div>
  </div>

 </div>
</div>