config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    # public/homes
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    # public/items
    resources :items, only: [:index, :show]

    # public/customers
    get 'customers/my_page' => 'customers#show', as: "show"
    get 'customers/information/edit' => 'customers#edit', as: "edit"
    patch 'customers/information' => 'customers#update', as: "update"
    get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"

    # public/cart_items
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # public/orders
    post 'orders/confirm' => "orders#confirm", as: "confirm"
    get 'orders/complete' => "orders#complete", as: "complete"
    resources :orders, only: [:new, :index, :show, :create]

    # public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    # admin/homes
    get '/' => "homes#top", as: "top"

    # admin/items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # admin/genres
    resources :genres, only: [:index, :create, :edit, :update]

    # admin/customers
    resources :customers, only: [:index, :show, :edit, :update]

    # admin/orders
    resources :orders, only: [:show, :update]

    # admin/order_details
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # devise_for :admin, controllers: {
  # sessions: "admin/sessions"
  # }

end

app/models/genre.rb
class Genre < ApplicationRecord
 # ジャンル名のバリデーション設定
 validates :name, presence: true
 # genre（1）はitemを（N）複数持っている
 has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
   # Viewのform_withへ渡すための「空のモデル」を生成する
   @genre = Genre.new
   # 全てのジャンルデータを取得する
   @genres = Genre.all
  end

  def create
   # データを受け取り新規登録するためのインスタンス作成
   @genre = Genre.new(genre_params)
   # データをデータベースに保存する
   @genre.save
   # ジャンル登録後、ジャンル一覧画面にリダイレクト
   redirect_to admin_genres_path
  end

  def edit
   # 登録済みのデータを取得する
   @genre = Genre.find(params[:id])
  end

  def update
   # 登録済みのデータを取得する
   @genre = Genre.find(params[:id])
   # ジャンルの更新が成功した場合
   if @genre.update(genre_params)
    # ジャンル一覧画面にリダイレクト
    redirect_to admin_genres_path
   else
    # falseの場合、編集画面を再表示する
    render :edit
   end
  end

  private
  # ジャンルデータのストロングパラメータ
  def genre_params
   params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
   <style>
    label {
     padding-right: 5%;
    }

    .field_with_errors {
     display: contents;
    }

    /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
    @media screen and (max-width: 768px) {
     h3 {
      font-size: 20px;
     }

     .field, .btn-success {
      font-size: 13px;
     }
    }
   </style>

   <div class="col-12">
    <h3 style="padding: 10px 0 30px 5%;">
     <span style="background-color: #e6dcdf;">
      ジャンル編集
     </span>
    </h3>

    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
     <div class="field">
      <label for="admin_genre">ジャンル名</label>
      <%= f.text_field :name, size: "15" %>
      <%= f.submit "変更を保存", class: "btn btn-success offset-1" %>
     </div>
    <% end %>

   </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <style>
   label {
    padding-right: 5%;
   }

   table {
    margin-top: 20px;
   }

   thead {
    color: rgba(0, 0, 0, 0.6);
    background-color: #e6dcdf;
   }

   /* タブレット縦置きサイズ（768px）以下の際に適用される設定 */
   @media screen and (max-width: 768px) {
    h3 {
     font-size: 20px;
    }

    .field, .table-inverse, .btn-success {
     font-size: 13px;
    }

    .table-inverse {
     width: 80%;
    }

    .new_name {
     width: 120px;
    }

   }

  </style>

  <div class="col-lg-12 col-md-10 col-sm-8">
   <h3 style="padding: 10px 0 30px 5%;">
    <span style="background-color: #e6dcdf;">
     ジャンル一覧・追加
    </span>
   </h3>

   <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
    <div class="field">
     <label for="admin_genre">ジャンル名</label>
     <%= f.text_field :name, class: "new_name" %>
     <%= f.submit "新規登録", class: "btn btn-success offset-1" %>
    </div>
   <% end %>
  </div>

  <div class="col-lg-12 col-md-10 col-sm-8">
   <table class="table table-inverse">

    <thead>
     <tr>
      <th>ジャンル</th>
      <th></th>
     </tr>
    </thead>

    <tbody style="color: rgba(0, 0, 0, 0.6);">
     <% @genres.each do |genre| %>
     <tr>
      <td>
       <%= genre.name %>
      </td>
      <td>
       <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success offset-1" %>
      </td>
     </tr>
     <% end %>
    </tbody>

   </table>
  </div>

 </div>
</div>