config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    # public/homes
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    # public/items
    resources :items, only: [:index, :show]

    # public/customers
    get 'customers/my_page' => 'customers#show', as: "show"
    get 'customers/information/edit' => 'customers#edit', as: "edit"
    patch 'customers/information' => 'customers#update', as: "update"
    get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"

    # public/cart_items
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # public/orders
    post 'orders/confirm' => "orders#confirm", as: "confirm"
    get 'orders/complete' => "orders#complete", as: "complete"
    resources :orders, only: [:new, :index, :show, :create]

    # public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    # admin/homes
    get '/' => "homes#top", as: "top"

    # admin/items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # admin/genres
    resources :genres, only: [:index, :create, :edit, :update]

    # admin/customers
    resources :customers, only: [:index, :show, :edit, :update]

    # admin/orders
    resources :orders, only: [:show, :update]

    # admin/order_details
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # devise_for :admin, controllers: {
  # sessions: "admin/sessions"
  # }

end

app/models/address.rb
class Address < ApplicationRecord
 # address（N）はcustomer（1）に属する
 belongs_to :customer

 validates :name, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true

 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 # cart_item（N）はitem（1）に属する
 belongs_to :item
 # cart_item（N）はcustomer（1）に属する
 belongs_to :customer

 # 小計を求めるメソッド
 def subtotal
  item.with_tax_price * amount
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # customer（1）はaddress（N）を複数持っている
  has_many :addresses
  # customer（1）はcart_item（N）を複数持っている
  has_many :cart_items
  # customer（1）はorder（N）を複数持っている
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # 会員フルネーム（漢字）用のメソッド
  def full_name
   self.last_name + " " + self.first_name
  end

  # 会員フルネーム（カナ）用のメソッド
  def full_name_kana
   self.last_name_kana + " " + self.first_name_kana
  end

  enum is_deleted: { no_active: true, active: false}
end

app/models/genre.rb
class Genre < ApplicationRecord
 # ジャンル名のバリデーション設定
 validates :name, presence: true
 # genre（1）はitemを（N）複数持っている
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 # Itemモデルに image を持たせる
 has_one_attached :image
 # item（N）はgenre（1）に属する
 belongs_to :genre
 # item（1）はcart_item（N）を複数持っている
 has_many :cart_items
 # item（1）はorder_detail（N）を複数持っている
 has_many :order_details

 validates :image, presence: true
 validates :name, presence: true
 validates :introduction, presence: true
 validates :genre_id, presence: true
 validates :price, presence: true

 enum is_active: { active: true, no_active: false }

 # 消費税を求めるメソッド
 def with_tax_price
  (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
 # order（N）はcustomer（1）に属する
 belongs_to :customer
 # order（1）はorder_detail（N）を複数持っている
 has_many :order_details

 # 小計を求めるメソッド
 def subtotal
  item.with_tax_price * amount
 end

 enum order_status: { wait: 0, deposited: 1, make: 2, preparation: 3, sent: 4 }
 enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 # order_detail（N）はorder（1）に属する
 belongs_to :order
 # order_detail（N）はitem（1）に属する
 belongs_to :item

 enum crafting_status: { impossible: 0, wait: 1, make: 2, manufactured: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
   # Viewのform_withへ渡すための「空のモデル」を生成する
   @genre = Genre.new
   # 全てのジャンルデータを取得する
   @genres = Genre.all
  end

  def create
   # データを受け取り新規登録するためのインスタンス作成
   @genre = Genre.new(genre_params)
   # データをデータベースに保存する
   @genre.save
   # ジャンル登録後、ジャンル一覧画面にリダイレクト
   redirect_to admin_genres_path
  end

  def edit
   # 登録済みのデータを取得する
   @genre = Genre.find(params[:id])
  end

  def update
   # 登録済みのデータを取得する
   @genre = Genre.find(params[:id])
   # ジャンルの更新が成功した場合
   if @genre.update(genre_params)
    # ジャンル一覧画面にリダイレクト
    redirect_to admin_genres_path
   else
    # falseの場合、編集画面を再表示する
    render :edit
   end
  end

  private
  # ジャンルデータのストロングパラメータ
  def genre_params
   params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
   # ordersテーブルに保存されている全てのデータを取得する
   @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!

  def index
   # itemsテーブルに保存されている全てのデータを取得する
   @items = Item.page(params[:page])
  end

  def new
   # Viewのform_withへ渡すための「空のモデル」を生成する
   @item = Item.new
   # genresテーブルに保存されている全てのデータを取得する
   @genres = Genre.all
  end

  def create
   # データを受け取り新規登録するためのインスタンス作成
   @item = Item.new(item_params)
   # データをデータベースに保存する
   if @item.save
    # 商品詳細画面にリダイレクト
    redirect_to admin_item_path(@item.id)
   # 保存に失敗した場合
   else
    # 商品新規登録画面を再表示
    @genres = Genre.all
    render :new
   end
  end

  def show
   # レコードを1件だけ取得
   @item = Item.find(params[:id])
  end

  def edit
   # レコードを1件だけ取得
   @item = Item.find(params[:id])
   # genresテーブルに保存されている全てのデータを取得する
   @genres = Genre.all
  end

  def update
   # レコードを1件だけ取得
   @item = Item.find(params[:id])
   @item.update(item_params)
   # 商品詳細画面にリダイレクト
   redirect_to admin_item_path(@item.id)
  end

  private
  # 商品データのストロングパラメータ
  def item_params
   params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 private
 # サインイン後のリダイレクト先を指定
 def after_sign_in_path_for(resource_or_scope)
  if resource_or_scope.is_a?(Admin)
   # 管理者の場合は注文画面一覧画面
   admin_top_path
  else
   # 上記に当てはまらない（顧客）場合、ルートパス
   root_path
  end
 end

 # サインアウト後のリダイレクト先を設定
 def after_sign_out_path_for(resource_or_scope)
  # 管理者の場合
  if resource_or_scope == :admin
   # 管理者ログイン画面
   new_admin_session_path
  # 顧客の場合
  elsif resource_or_scope == :public
   # ルートパス
   root_path
  else
   root_path
  end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/6eb889a2d4.js" crossorigin="anonymous"></script>
  </head>

  <style>
   .color {
    background-color: #dbafbd;
   }

   .bkcolor {
    background-color: #f6ebee;
   }

   .text {
    color : rgba(0, 0, 0, 0.6);
   }

   .logo {
    text-align: center;
    padding: 1rem 0.5rem 0.5rem;
   }

   footer {
    background-color: #dbafbd;
    margin-top: 20px;
   }

   p {
    font-size: 15px
   }

   .customer_name {
    margin-left: 20%;
   }

   /* タブレット横置きサイズ（1024px）以下の際に適用される設定 */
   @media screen and (max-width:1024px) {
    .customer_name {
     margin-left: 0;
    }
   }

   /* スマートフォンサイズ（425px）以下の際に適用される設定 */
   @media screen and (max-width:425px) {
    .navbar-brand {
     margin-right: 0;
    }
   }
  </style>

  <body class="bkcolor text">
    <!-- ここからヘッダー -->
    <header class="color">
     <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
       <!-- アイコン -->
       <%= link_to '/', class: "navbar-brand" do %>
        <%= image_tag "logo(2).png", size: "90x30" %>
       <% end %>

       <div class="customer_name">
        <% if customer_signed_in? %>
         ようこそ、<%= current_customer.last_name %>さん！
        <% end %>
       </div>

       <!-- ナビゲーションバー -->
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <!-- 条件1：admin（管理者）はログインしていますか？ -->
        <% if admin_signed_in? %>

         <!-- trueの場合、ここから管理者用のヘッダー -->
         <!-- ここから商品一覧ボタン -->
         <li>
          <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
         </li>
         <!-- ここまで商品一覧ボタン -->

         <!-- ここから会員一覧ボタン -->
         <li>
          <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
         </li>
         <!-- ここまで会員一覧ボタン -->

         <!-- ここから注文履歴一覧ボタン -->
         <li>
          <%= link_to "注文履歴一覧", admin_top_path, class: "nav-link" %>
         </li>
         <!-- ここまで注文履歴一覧ボタン -->

         <!-- ここからジャンル一覧ボタン -->
          <li>
           <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
         <!-- ここまでジャンル一覧ボタン -->

         <!-- ここからログアウトボタン -->
         <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
         </li>
         <!-- ここまでログアウトボタン -->
         <!-- ここまで管理者用のヘッダー -->

        <!-- 条件1がfalse、条件2：customer（顧客）はログインしていますか？ -->
        <% elsif customer_signed_in? %>

         <!-- trueの場合、ここから顧客用のヘッダー -->
         <!-- ここからマイページボタン -->
         <li>
          <%= link_to show_path, class: "nav-link" do %>
           <i class="fa-solid fa-circle-user"></i>
           マイページ
          <% end %>
         </li>
         <!-- ここまでマイページボタン -->

         <!-- ここから商品一覧ボタン-->
         <li>
          <%= link_to items_path, class: "nav-link" do %>
           <i class="fa-solid fa-cake-candles"></i>
           商品一覧
          <% end %>
         </li>
         <!-- ここまで商品一覧ボタン-->

         <!-- ここからカートボタン -->
         <li>
          <%= link_to cart_items_path, class: "nav-link" do %>
           <i class="fa-solid fa-cart-shopping"></i>
           カート
          <% end %>
         </li>
         <!-- ここまでカートボタン -->

         <!-- ここからログアウトボタン -->
         <li>
          <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link" do %>
           <i class="fas fa-sign-out-alt"></i>
           ログアウト
          <% end %>
         </li>
        <!-- ここまでログアウトボタン -->
        <!-- ここまで顧客用のヘッダー -->

        <!-- 条件1、2が全てfalseの場合、以下処理を行う -->
        <% else %>

         <!-- ここから管理者も顧客もログアウト状態用のヘッダー -->
         <!-- ここからAboutボタン -->
         <li>
          <%= link_to about_path, class: "nav-link" do %>
           <i class="fa-solid fa-mug-hot"></i>
           About
          <% end %>
         </li>
         <!-- ここまでAboutボタン -->

         <!-- ここから商品一覧ボタン -->
         <li>
          <%= link_to items_path, class: "nav-link" do %>
           <i class="fa-solid fa-cake-candles"></i>
           商品一覧
          <% end %>
         </li>
         <!-- ここまで商品一覧ボタン -->

         <!-- ここから新規登録ボタン -->
         <li>
          <%= link_to new_customer_registration_path, class: "nav-link" do %>
           <i class="fas fa-user-plus"></i>
           新規登録
          <% end %>
         </li>
         <!-- ここまで新規登録ボタン -->

         <!-- ここからログインボタン -->
         <li>
          <%= link_to new_customer_session_path, class: "nav-link" do %>
           <i class="fas fa-sign-in-alt"></i>
           ログイン
          <% end %>
         </li>
         <!-- ここまでログインボタン -->

        <% end %>
        <!-- ここまで管理者も顧客もログアウト状態用のヘッダー -->

        </ul>
       </div>

      </div>
     </nav>

    </header>
    <!-- ここまでヘッダー -->
    <main>
     <p id="notice">
      <%= flash[:notice] %>
     </p>
     <%= yield %>
    </main>

    <footer>
     <div class="container">
      <div class="row">
       <div class="mx-auto">
        <!-- アイコン -->
        <div class="logo">
         <%= link_to '/' do %>
          <%= image_tag "logo(2).png", size: "120x40" %>
         <% end %>
        </div>
        <p>copyright © nagano_cake All rights reserved.</p>
       </div>
      </div>
     </div>
    </footer>

  </body>
</html>